### ISSUE TITLE
Unstoppable Name Error

### ISSUE THREAD

**Issue by mhzbrain** [nahueldsanchez/dvd_brownie#2]
Hi, found your project and am planning to work through the dvd challenges using it. I'll try to comment when I run into things...

First thing is a runtime error in test_solution.py for the Unstoppable problem. I am getting: 'NameError: name 'brownie' is not defined' referring to the 'with brownie.reverts():' line. Turns out brownie is not imported in total so this name doesn't in fact exist. Easy fix.

Everything else perfect so far, thanks for creating this!

**Comment by nahueldsanchez** [comment]
Hi @mhzbrain thanks for your comment. I hope that you find this project useful. Don't hesitate to reach out if you need any help :). Regarding the issue you have reported I already fixed it, thank you!
