### ISSUE TITLE
Setup fails - Naive Receiver

### ISSUE THREAD

**Issue by mhzbrain** [nahueldsanchez/dvd_brownie#3]
Sorry about this, but there is another small nitpick. For me the test_scenario_setup(): for Naive Receiver fails out of the box because the asserts for the balances don't have matching units. Looks like the left hand side is wei and right hand side is ether in this case.

**Comment by nahueldsanchez** [comment]
No worries and thanks for bringing this up. I've fixed it.

Thanks again for reporting it, if you find any other issues, please let me know!

**Comment by nahueldsanchez** [comment]
No worries and thanks for bringing this up. I've fixed it.

Thanks again for reporting it, if you find any other issues, please let me know!
